os: linux
dist: xenial
language: node_js
node_js:
- '12'
cache: yarn
jobs:
  include:
  - name: Standalone MacOS on MacOS
    os: osx
    osx_image: xcode11.3
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
    script:
    - cd gulp
    - yarn gulp build.standalone-prod || travis_terminate 1
    - yarn gulp standalone.prepare
    - yarn gulp standalone.package.prod.darwin64
    - cd ..
    - tar -czf shapez.io-standalone.tar.gz tmp_standalone_files/shapez.io-standalone*
    deploy:
      provider: releases
      api_key:
        secure: PleoviZ4vUNNEAcSM1p/X2S4S0BMjiYT7ORgtTaLA7OtnUKoHkWQBDgIrIB0YKl/dFpHkIDIGirR4+q6K1Zx+kgLrC0lP01mfurgM6PzYKDTMpbmynfzrRtltoBf2zthIfxMlFpOH/4HXiZzHLeVinSybQQtHDjEH+fgSj9eEZDADLGL33Z76GsfnUyi6Djq9659JuChYWmCXz4+zVo/V3uZCREYge11X/Dyp8dbxVIU0dimZATYkeycvs1S347app+PJFyaAoxkBM2vh91Rcc7RtQdj7wu740A8kyg/m+tvXYJOeSOSpbONXkTysSeOam4moptMoDQu+vwjuLmlH1jSzjQ5qnL48Ie6nVTuSvVgnLPWC/2h+C3Mi2Ai2zE3zO3dIH3q0/nAWHycJD/J4b4mv4OGuwtu4T0FeAgMfq0Xc5eCx3Q3lLgiOhM5iBdxvW75pbEmLyQti+zudONrS1ZJarctPXYlc1h/j552Xz+DEEOpI4SfwbdqUzI+GuEq/zizic+BNNIYqJagMsQh7X7jFwBWxPmMX6Nogi4YLdQ4XPhW1tmc6NewbhBYTWvIdeFw1xz3H24Ys/LEWq6REKEbXqBDcS5Eo9aqitgNZw8ZJ7mZhlrnyeGzaV37k7xjQsYJN8hB/eszyzoJT2YUHKPUXjluCMGMhdDcqZSrgXU=
      file: shapez.io-standalone.tar.gz
      draft: 'true'
      on:
        repo: Mariusmivw/shapez.io
        branch: test
      skip_cleanup: 'true'
  - name: Standalone Windows on Windows
    os: windows
    env:
    - YARN_GPG=no
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    matrix:
    - JDK="adopt@1.8"
    before_install:
    - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
    - source $GRAVIS/install-jdk
    - choco install git-lfs -y -f || echo "0"
    - choco install ffmpeg --version=4.2.3
    - choco install wget
    - export PATH=/C/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin:$PATH
    - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/avicap32.dll
      -P /C/Windows/System32/
    - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/msvfw32.dll
      -P /C/Windows/System32/
    script:
    - cd gulp
    - yarn gulp build.standalone-prod || travis_terminate 1
    - yarn gulp standalone.prepare
    - yarn gulp standalone.package.prod.win64
    - yarn gulp standalone.package.prod.win32
    - cd ..
  fast_finish: true
install:
- git lfs install
- git lfs pull
- yarn
- cd electron
- yarn
- cd ..
- cd gulp
- yarn
- cd ..
